### ISSUE TITLE
Integrate directly without SNS

### ISSUE THREAD

**Issue by monal94** [ExpediaDotCom/cloudtrail-log-analytics#3]
Hi, I wanted to know the reason you went with S3 -> SNS notification delivery model when a S3 based lambda event trigger is already available. This would reduce cost and remove redundant SNS trigger.
Refer: https://docs.aws.amazon.com/lambda/latest/dg/with-s3.html

**Comment by kchowhan** [comment]
@monal94 The reason is with s3 to lambda you are very much limited to how you define prefixes for the lambda invocation and if someone has defined a root level prefix for lambda invocation then other's can't have another invocation defined. I prefer triggering based of SNS for CloudTrail. SNS event is auto generated by CloudTrail itself whenever it deposits the file in S3. The configuration is not done one S3 rather done within CloudTrail itself.
